package com.wisenable.dms.datasource.mappers;


import com.wisenable.dms.datasource.entities.Prescription;
import com.wisenable.dms.datasource.entities.PrescriptionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PrescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int countByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int deleteByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int insert(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int insertSelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    List<Prescription> selectByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    Prescription selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Prescription record, @Param("example") PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Prescription record, @Param("example") PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Prescription record);
}