package com.wisenable.dms.datasource.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PrescriptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public PrescriptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShipperIdIsNull() {
            addCriterion("shipper_id is null");
            return (Criteria) this;
        }

        public Criteria andShipperIdIsNotNull() {
            addCriterion("shipper_id is not null");
            return (Criteria) this;
        }

        public Criteria andShipperIdEqualTo(Long value) {
            addCriterion("shipper_id =", value, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdNotEqualTo(Long value) {
            addCriterion("shipper_id <>", value, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdGreaterThan(Long value) {
            addCriterion("shipper_id >", value, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shipper_id >=", value, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdLessThan(Long value) {
            addCriterion("shipper_id <", value, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdLessThanOrEqualTo(Long value) {
            addCriterion("shipper_id <=", value, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdIn(List<Long> values) {
            addCriterion("shipper_id in", values, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdNotIn(List<Long> values) {
            addCriterion("shipper_id not in", values, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdBetween(Long value1, Long value2) {
            addCriterion("shipper_id between", value1, value2, "shipperId");
            return (Criteria) this;
        }

        public Criteria andShipperIdNotBetween(Long value1, Long value2) {
            addCriterion("shipper_id not between", value1, value2, "shipperId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Long value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Long value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Long> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Long> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andOdSphIsNull() {
            addCriterion("od_sph is null");
            return (Criteria) this;
        }

        public Criteria andOdSphIsNotNull() {
            addCriterion("od_sph is not null");
            return (Criteria) this;
        }

        public Criteria andOdSphEqualTo(String value) {
            addCriterion("od_sph =", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphNotEqualTo(String value) {
            addCriterion("od_sph <>", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphGreaterThan(String value) {
            addCriterion("od_sph >", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphGreaterThanOrEqualTo(String value) {
            addCriterion("od_sph >=", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphLessThan(String value) {
            addCriterion("od_sph <", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphLessThanOrEqualTo(String value) {
            addCriterion("od_sph <=", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphLike(String value) {
            addCriterion("od_sph like", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphNotLike(String value) {
            addCriterion("od_sph not like", value, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphIn(List<String> values) {
            addCriterion("od_sph in", values, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphNotIn(List<String> values) {
            addCriterion("od_sph not in", values, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphBetween(String value1, String value2) {
            addCriterion("od_sph between", value1, value2, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdSphNotBetween(String value1, String value2) {
            addCriterion("od_sph not between", value1, value2, "odSph");
            return (Criteria) this;
        }

        public Criteria andOdCylIsNull() {
            addCriterion("od_cyl is null");
            return (Criteria) this;
        }

        public Criteria andOdCylIsNotNull() {
            addCriterion("od_cyl is not null");
            return (Criteria) this;
        }

        public Criteria andOdCylEqualTo(String value) {
            addCriterion("od_cyl =", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylNotEqualTo(String value) {
            addCriterion("od_cyl <>", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylGreaterThan(String value) {
            addCriterion("od_cyl >", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylGreaterThanOrEqualTo(String value) {
            addCriterion("od_cyl >=", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylLessThan(String value) {
            addCriterion("od_cyl <", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylLessThanOrEqualTo(String value) {
            addCriterion("od_cyl <=", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylLike(String value) {
            addCriterion("od_cyl like", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylNotLike(String value) {
            addCriterion("od_cyl not like", value, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylIn(List<String> values) {
            addCriterion("od_cyl in", values, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylNotIn(List<String> values) {
            addCriterion("od_cyl not in", values, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylBetween(String value1, String value2) {
            addCriterion("od_cyl between", value1, value2, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdCylNotBetween(String value1, String value2) {
            addCriterion("od_cyl not between", value1, value2, "odCyl");
            return (Criteria) this;
        }

        public Criteria andOdAxisIsNull() {
            addCriterion("od_axis is null");
            return (Criteria) this;
        }

        public Criteria andOdAxisIsNotNull() {
            addCriterion("od_axis is not null");
            return (Criteria) this;
        }

        public Criteria andOdAxisEqualTo(String value) {
            addCriterion("od_axis =", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisNotEqualTo(String value) {
            addCriterion("od_axis <>", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisGreaterThan(String value) {
            addCriterion("od_axis >", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisGreaterThanOrEqualTo(String value) {
            addCriterion("od_axis >=", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisLessThan(String value) {
            addCriterion("od_axis <", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisLessThanOrEqualTo(String value) {
            addCriterion("od_axis <=", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisLike(String value) {
            addCriterion("od_axis like", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisNotLike(String value) {
            addCriterion("od_axis not like", value, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisIn(List<String> values) {
            addCriterion("od_axis in", values, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisNotIn(List<String> values) {
            addCriterion("od_axis not in", values, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisBetween(String value1, String value2) {
            addCriterion("od_axis between", value1, value2, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdAxisNotBetween(String value1, String value2) {
            addCriterion("od_axis not between", value1, value2, "odAxis");
            return (Criteria) this;
        }

        public Criteria andOdVaIsNull() {
            addCriterion("od_va is null");
            return (Criteria) this;
        }

        public Criteria andOdVaIsNotNull() {
            addCriterion("od_va is not null");
            return (Criteria) this;
        }

        public Criteria andOdVaEqualTo(String value) {
            addCriterion("od_va =", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaNotEqualTo(String value) {
            addCriterion("od_va <>", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaGreaterThan(String value) {
            addCriterion("od_va >", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaGreaterThanOrEqualTo(String value) {
            addCriterion("od_va >=", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaLessThan(String value) {
            addCriterion("od_va <", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaLessThanOrEqualTo(String value) {
            addCriterion("od_va <=", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaLike(String value) {
            addCriterion("od_va like", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaNotLike(String value) {
            addCriterion("od_va not like", value, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaIn(List<String> values) {
            addCriterion("od_va in", values, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaNotIn(List<String> values) {
            addCriterion("od_va not in", values, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaBetween(String value1, String value2) {
            addCriterion("od_va between", value1, value2, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdVaNotBetween(String value1, String value2) {
            addCriterion("od_va not between", value1, value2, "odVa");
            return (Criteria) this;
        }

        public Criteria andOdPdIsNull() {
            addCriterion("od_pd is null");
            return (Criteria) this;
        }

        public Criteria andOdPdIsNotNull() {
            addCriterion("od_pd is not null");
            return (Criteria) this;
        }

        public Criteria andOdPdEqualTo(String value) {
            addCriterion("od_pd =", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdNotEqualTo(String value) {
            addCriterion("od_pd <>", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdGreaterThan(String value) {
            addCriterion("od_pd >", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdGreaterThanOrEqualTo(String value) {
            addCriterion("od_pd >=", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdLessThan(String value) {
            addCriterion("od_pd <", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdLessThanOrEqualTo(String value) {
            addCriterion("od_pd <=", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdLike(String value) {
            addCriterion("od_pd like", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdNotLike(String value) {
            addCriterion("od_pd not like", value, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdIn(List<String> values) {
            addCriterion("od_pd in", values, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdNotIn(List<String> values) {
            addCriterion("od_pd not in", values, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdBetween(String value1, String value2) {
            addCriterion("od_pd between", value1, value2, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdPdNotBetween(String value1, String value2) {
            addCriterion("od_pd not between", value1, value2, "odPd");
            return (Criteria) this;
        }

        public Criteria andOdAddIsNull() {
            addCriterion("od_add is null");
            return (Criteria) this;
        }

        public Criteria andOdAddIsNotNull() {
            addCriterion("od_add is not null");
            return (Criteria) this;
        }

        public Criteria andOdAddEqualTo(String value) {
            addCriterion("od_add =", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddNotEqualTo(String value) {
            addCriterion("od_add <>", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddGreaterThan(String value) {
            addCriterion("od_add >", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddGreaterThanOrEqualTo(String value) {
            addCriterion("od_add >=", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddLessThan(String value) {
            addCriterion("od_add <", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddLessThanOrEqualTo(String value) {
            addCriterion("od_add <=", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddLike(String value) {
            addCriterion("od_add like", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddNotLike(String value) {
            addCriterion("od_add not like", value, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddIn(List<String> values) {
            addCriterion("od_add in", values, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddNotIn(List<String> values) {
            addCriterion("od_add not in", values, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddBetween(String value1, String value2) {
            addCriterion("od_add between", value1, value2, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdAddNotBetween(String value1, String value2) {
            addCriterion("od_add not between", value1, value2, "odAdd");
            return (Criteria) this;
        }

        public Criteria andOdPhIsNull() {
            addCriterion("od_ph is null");
            return (Criteria) this;
        }

        public Criteria andOdPhIsNotNull() {
            addCriterion("od_ph is not null");
            return (Criteria) this;
        }

        public Criteria andOdPhEqualTo(String value) {
            addCriterion("od_ph =", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhNotEqualTo(String value) {
            addCriterion("od_ph <>", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhGreaterThan(String value) {
            addCriterion("od_ph >", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhGreaterThanOrEqualTo(String value) {
            addCriterion("od_ph >=", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhLessThan(String value) {
            addCriterion("od_ph <", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhLessThanOrEqualTo(String value) {
            addCriterion("od_ph <=", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhLike(String value) {
            addCriterion("od_ph like", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhNotLike(String value) {
            addCriterion("od_ph not like", value, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhIn(List<String> values) {
            addCriterion("od_ph in", values, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhNotIn(List<String> values) {
            addCriterion("od_ph not in", values, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhBetween(String value1, String value2) {
            addCriterion("od_ph between", value1, value2, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdPhNotBetween(String value1, String value2) {
            addCriterion("od_ph not between", value1, value2, "odPh");
            return (Criteria) this;
        }

        public Criteria andOdBcIsNull() {
            addCriterion("od_bc is null");
            return (Criteria) this;
        }

        public Criteria andOdBcIsNotNull() {
            addCriterion("od_bc is not null");
            return (Criteria) this;
        }

        public Criteria andOdBcEqualTo(String value) {
            addCriterion("od_bc =", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcNotEqualTo(String value) {
            addCriterion("od_bc <>", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcGreaterThan(String value) {
            addCriterion("od_bc >", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcGreaterThanOrEqualTo(String value) {
            addCriterion("od_bc >=", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcLessThan(String value) {
            addCriterion("od_bc <", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcLessThanOrEqualTo(String value) {
            addCriterion("od_bc <=", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcLike(String value) {
            addCriterion("od_bc like", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcNotLike(String value) {
            addCriterion("od_bc not like", value, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcIn(List<String> values) {
            addCriterion("od_bc in", values, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcNotIn(List<String> values) {
            addCriterion("od_bc not in", values, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcBetween(String value1, String value2) {
            addCriterion("od_bc between", value1, value2, "odBc");
            return (Criteria) this;
        }

        public Criteria andOdBcNotBetween(String value1, String value2) {
            addCriterion("od_bc not between", value1, value2, "odBc");
            return (Criteria) this;
        }

        public Criteria andOsSphIsNull() {
            addCriterion("os_sph is null");
            return (Criteria) this;
        }

        public Criteria andOsSphIsNotNull() {
            addCriterion("os_sph is not null");
            return (Criteria) this;
        }

        public Criteria andOsSphEqualTo(String value) {
            addCriterion("os_sph =", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphNotEqualTo(String value) {
            addCriterion("os_sph <>", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphGreaterThan(String value) {
            addCriterion("os_sph >", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphGreaterThanOrEqualTo(String value) {
            addCriterion("os_sph >=", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphLessThan(String value) {
            addCriterion("os_sph <", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphLessThanOrEqualTo(String value) {
            addCriterion("os_sph <=", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphLike(String value) {
            addCriterion("os_sph like", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphNotLike(String value) {
            addCriterion("os_sph not like", value, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphIn(List<String> values) {
            addCriterion("os_sph in", values, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphNotIn(List<String> values) {
            addCriterion("os_sph not in", values, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphBetween(String value1, String value2) {
            addCriterion("os_sph between", value1, value2, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsSphNotBetween(String value1, String value2) {
            addCriterion("os_sph not between", value1, value2, "osSph");
            return (Criteria) this;
        }

        public Criteria andOsCylIsNull() {
            addCriterion("os_cyl is null");
            return (Criteria) this;
        }

        public Criteria andOsCylIsNotNull() {
            addCriterion("os_cyl is not null");
            return (Criteria) this;
        }

        public Criteria andOsCylEqualTo(String value) {
            addCriterion("os_cyl =", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylNotEqualTo(String value) {
            addCriterion("os_cyl <>", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylGreaterThan(String value) {
            addCriterion("os_cyl >", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylGreaterThanOrEqualTo(String value) {
            addCriterion("os_cyl >=", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylLessThan(String value) {
            addCriterion("os_cyl <", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylLessThanOrEqualTo(String value) {
            addCriterion("os_cyl <=", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylLike(String value) {
            addCriterion("os_cyl like", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylNotLike(String value) {
            addCriterion("os_cyl not like", value, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylIn(List<String> values) {
            addCriterion("os_cyl in", values, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylNotIn(List<String> values) {
            addCriterion("os_cyl not in", values, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylBetween(String value1, String value2) {
            addCriterion("os_cyl between", value1, value2, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsCylNotBetween(String value1, String value2) {
            addCriterion("os_cyl not between", value1, value2, "osCyl");
            return (Criteria) this;
        }

        public Criteria andOsAxisIsNull() {
            addCriterion("os_axis is null");
            return (Criteria) this;
        }

        public Criteria andOsAxisIsNotNull() {
            addCriterion("os_axis is not null");
            return (Criteria) this;
        }

        public Criteria andOsAxisEqualTo(String value) {
            addCriterion("os_axis =", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisNotEqualTo(String value) {
            addCriterion("os_axis <>", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisGreaterThan(String value) {
            addCriterion("os_axis >", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisGreaterThanOrEqualTo(String value) {
            addCriterion("os_axis >=", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisLessThan(String value) {
            addCriterion("os_axis <", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisLessThanOrEqualTo(String value) {
            addCriterion("os_axis <=", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisLike(String value) {
            addCriterion("os_axis like", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisNotLike(String value) {
            addCriterion("os_axis not like", value, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisIn(List<String> values) {
            addCriterion("os_axis in", values, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisNotIn(List<String> values) {
            addCriterion("os_axis not in", values, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisBetween(String value1, String value2) {
            addCriterion("os_axis between", value1, value2, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsAxisNotBetween(String value1, String value2) {
            addCriterion("os_axis not between", value1, value2, "osAxis");
            return (Criteria) this;
        }

        public Criteria andOsVaIsNull() {
            addCriterion("os_va is null");
            return (Criteria) this;
        }

        public Criteria andOsVaIsNotNull() {
            addCriterion("os_va is not null");
            return (Criteria) this;
        }

        public Criteria andOsVaEqualTo(String value) {
            addCriterion("os_va =", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaNotEqualTo(String value) {
            addCriterion("os_va <>", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaGreaterThan(String value) {
            addCriterion("os_va >", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaGreaterThanOrEqualTo(String value) {
            addCriterion("os_va >=", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaLessThan(String value) {
            addCriterion("os_va <", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaLessThanOrEqualTo(String value) {
            addCriterion("os_va <=", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaLike(String value) {
            addCriterion("os_va like", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaNotLike(String value) {
            addCriterion("os_va not like", value, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaIn(List<String> values) {
            addCriterion("os_va in", values, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaNotIn(List<String> values) {
            addCriterion("os_va not in", values, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaBetween(String value1, String value2) {
            addCriterion("os_va between", value1, value2, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsVaNotBetween(String value1, String value2) {
            addCriterion("os_va not between", value1, value2, "osVa");
            return (Criteria) this;
        }

        public Criteria andOsPdIsNull() {
            addCriterion("os_pd is null");
            return (Criteria) this;
        }

        public Criteria andOsPdIsNotNull() {
            addCriterion("os_pd is not null");
            return (Criteria) this;
        }

        public Criteria andOsPdEqualTo(String value) {
            addCriterion("os_pd =", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdNotEqualTo(String value) {
            addCriterion("os_pd <>", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdGreaterThan(String value) {
            addCriterion("os_pd >", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdGreaterThanOrEqualTo(String value) {
            addCriterion("os_pd >=", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdLessThan(String value) {
            addCriterion("os_pd <", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdLessThanOrEqualTo(String value) {
            addCriterion("os_pd <=", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdLike(String value) {
            addCriterion("os_pd like", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdNotLike(String value) {
            addCriterion("os_pd not like", value, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdIn(List<String> values) {
            addCriterion("os_pd in", values, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdNotIn(List<String> values) {
            addCriterion("os_pd not in", values, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdBetween(String value1, String value2) {
            addCriterion("os_pd between", value1, value2, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsPdNotBetween(String value1, String value2) {
            addCriterion("os_pd not between", value1, value2, "osPd");
            return (Criteria) this;
        }

        public Criteria andOsAddIsNull() {
            addCriterion("os_add is null");
            return (Criteria) this;
        }

        public Criteria andOsAddIsNotNull() {
            addCriterion("os_add is not null");
            return (Criteria) this;
        }

        public Criteria andOsAddEqualTo(String value) {
            addCriterion("os_add =", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddNotEqualTo(String value) {
            addCriterion("os_add <>", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddGreaterThan(String value) {
            addCriterion("os_add >", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddGreaterThanOrEqualTo(String value) {
            addCriterion("os_add >=", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddLessThan(String value) {
            addCriterion("os_add <", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddLessThanOrEqualTo(String value) {
            addCriterion("os_add <=", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddLike(String value) {
            addCriterion("os_add like", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddNotLike(String value) {
            addCriterion("os_add not like", value, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddIn(List<String> values) {
            addCriterion("os_add in", values, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddNotIn(List<String> values) {
            addCriterion("os_add not in", values, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddBetween(String value1, String value2) {
            addCriterion("os_add between", value1, value2, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsAddNotBetween(String value1, String value2) {
            addCriterion("os_add not between", value1, value2, "osAdd");
            return (Criteria) this;
        }

        public Criteria andOsPhIsNull() {
            addCriterion("os_ph is null");
            return (Criteria) this;
        }

        public Criteria andOsPhIsNotNull() {
            addCriterion("os_ph is not null");
            return (Criteria) this;
        }

        public Criteria andOsPhEqualTo(String value) {
            addCriterion("os_ph =", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhNotEqualTo(String value) {
            addCriterion("os_ph <>", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhGreaterThan(String value) {
            addCriterion("os_ph >", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhGreaterThanOrEqualTo(String value) {
            addCriterion("os_ph >=", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhLessThan(String value) {
            addCriterion("os_ph <", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhLessThanOrEqualTo(String value) {
            addCriterion("os_ph <=", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhLike(String value) {
            addCriterion("os_ph like", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhNotLike(String value) {
            addCriterion("os_ph not like", value, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhIn(List<String> values) {
            addCriterion("os_ph in", values, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhNotIn(List<String> values) {
            addCriterion("os_ph not in", values, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhBetween(String value1, String value2) {
            addCriterion("os_ph between", value1, value2, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsPhNotBetween(String value1, String value2) {
            addCriterion("os_ph not between", value1, value2, "osPh");
            return (Criteria) this;
        }

        public Criteria andOsBcIsNull() {
            addCriterion("os_bc is null");
            return (Criteria) this;
        }

        public Criteria andOsBcIsNotNull() {
            addCriterion("os_bc is not null");
            return (Criteria) this;
        }

        public Criteria andOsBcEqualTo(String value) {
            addCriterion("os_bc =", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcNotEqualTo(String value) {
            addCriterion("os_bc <>", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcGreaterThan(String value) {
            addCriterion("os_bc >", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcGreaterThanOrEqualTo(String value) {
            addCriterion("os_bc >=", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcLessThan(String value) {
            addCriterion("os_bc <", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcLessThanOrEqualTo(String value) {
            addCriterion("os_bc <=", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcLike(String value) {
            addCriterion("os_bc like", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcNotLike(String value) {
            addCriterion("os_bc not like", value, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcIn(List<String> values) {
            addCriterion("os_bc in", values, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcNotIn(List<String> values) {
            addCriterion("os_bc not in", values, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcBetween(String value1, String value2) {
            addCriterion("os_bc between", value1, value2, "osBc");
            return (Criteria) this;
        }

        public Criteria andOsBcNotBetween(String value1, String value2) {
            addCriterion("os_bc not between", value1, value2, "osBc");
            return (Criteria) this;
        }

        public Criteria andUsageIsNull() {
            addCriterion("usage is null");
            return (Criteria) this;
        }

        public Criteria andUsageIsNotNull() {
            addCriterion("usage is not null");
            return (Criteria) this;
        }

        public Criteria andUsageEqualTo(String value) {
            addCriterion("usage =", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotEqualTo(String value) {
            addCriterion("usage <>", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageGreaterThan(String value) {
            addCriterion("usage >", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageGreaterThanOrEqualTo(String value) {
            addCriterion("usage >=", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLessThan(String value) {
            addCriterion("usage <", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLessThanOrEqualTo(String value) {
            addCriterion("usage <=", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLike(String value) {
            addCriterion("usage like", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotLike(String value) {
            addCriterion("usage not like", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageIn(List<String> values) {
            addCriterion("usage in", values, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotIn(List<String> values) {
            addCriterion("usage not in", values, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageBetween(String value1, String value2) {
            addCriterion("usage between", value1, value2, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotBetween(String value1, String value2) {
            addCriterion("usage not between", value1, value2, "usage");
            return (Criteria) this;
        }

        public Criteria andDominantEyeIsNull() {
            addCriterion("dominant_eye is null");
            return (Criteria) this;
        }

        public Criteria andDominantEyeIsNotNull() {
            addCriterion("dominant_eye is not null");
            return (Criteria) this;
        }

        public Criteria andDominantEyeEqualTo(String value) {
            addCriterion("dominant_eye =", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeNotEqualTo(String value) {
            addCriterion("dominant_eye <>", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeGreaterThan(String value) {
            addCriterion("dominant_eye >", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeGreaterThanOrEqualTo(String value) {
            addCriterion("dominant_eye >=", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeLessThan(String value) {
            addCriterion("dominant_eye <", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeLessThanOrEqualTo(String value) {
            addCriterion("dominant_eye <=", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeLike(String value) {
            addCriterion("dominant_eye like", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeNotLike(String value) {
            addCriterion("dominant_eye not like", value, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeIn(List<String> values) {
            addCriterion("dominant_eye in", values, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeNotIn(List<String> values) {
            addCriterion("dominant_eye not in", values, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeBetween(String value1, String value2) {
            addCriterion("dominant_eye between", value1, value2, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andDominantEyeNotBetween(String value1, String value2) {
            addCriterion("dominant_eye not between", value1, value2, "dominantEye");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dms_prescription
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dms_prescription
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}